# Generated by Django 3.2.13 on 2022-04-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplydeposit_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplydeposit',
            name='sale_type',
        ),
    ]
