# Generated by Django 3.2.13 on 2022-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplydeposit_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydebt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplydeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplyloan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
