# Generated by Django 3.2.13 on 2022-04-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_processinginvoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingsale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.product'),
        ),
    ]
