# Generated by Django 3.2.13 on 2022-04-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_processingsale_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
