# Generated by Django 3.2.13 on 2022-04-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_auto_20220430_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplysale',
            name='price',
        ),
    ]
