# Generated by Django 4.1 on 2022-08-22 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_lastname_staff_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='guardian_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nok_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nok_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='relationship',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('SPOUSE', 'Spouse')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
