# Generated by Django 4.1 on 2022-08-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_guardian_address_staff_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('PROBATION', 'Probation'), ('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('SECURITY', 'Security'), ('MACHINE_OPERATOR', 'Machine Operator'), ('NYSC', 'NYSC'), ('IT_SIWES', 'IT/SIWES')], max_length=50),
        ),
    ]
