# Generated by Django 4.1 on 2022-08-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
