# Generated by Django 4.1 on 2022-08-24 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0005_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('SECURITY', 'Security'), ('MACHINE OPERATOR', 'Machine Operator'), ('NYSC', 'NYSC'), ('IT_SIWES', 'IT/SIWES')], max_length=50),
        ),
        migrations.CreateModel(
            name='discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_date', models.DateTimeField(auto_now_add=True)),
                ('offence', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
