# Generated by Django 4.1 on 2022-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staff_job_description_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='offence_date',
            field=models.DateTimeField(),
        ),
    ]
