# Generated by Django 4.1 on 2022-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='action',
            field=models.CharField(choices=[('CHECKIN', 'Checkin'), ('BREAKOUT', 'Breakout'), ('BREAKIN', 'Breakin'), ('CHECKOUT', 'Checkout')], max_length=255),
        ),
    ]
