# Generated by Django 4.1 on 2022-08-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_staff_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'check_date', 'action')},
        ),
    ]
