# Generated by Django 4.1 on 2022-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('SECURITY', 'Security'), ('MACHINE OPERATOR', 'Machine Operator'), ('NYSC', 'NYSC'), ('IT/SIWES', 'IT/SIWES')], max_length=50),
        ),
    ]
