# Generated by Django 4.1 on 2022-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staff_dob_staff_gender_alter_staff_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
