# Generated by Django 4.1 on 2022-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_staff_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='offence_date',
            field=models.DateField(),
        ),
    ]
