# Generated by Django 4.1 on 2022-08-30 07:28

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_discipline_offence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', upload_to=staff.models.upload_location),
        ),
    ]
