# Generated by Django 4.1 on 2022-08-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_attendance_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='identification',
            field=models.CharField(choices=[('', '----'), ('PVC', 'Voters Card'), ('NIN', 'National ID'), ('LICENCE', 'Drivers Licence'), ('PASSPORT', 'Passport')], max_length=30),
        ),
    ]
