# Generated by Django 3.2.13 on 2022-04-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_processsupply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
    ]
