# Generated by Django 3.2.13 on 2022-04-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_purchaseinvoice_customer_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='customer_d',
            new_name='supplier_d',
        ),
    ]
