# Generated by Django 3.2.13 on 2022-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_customer_d_purchaseinvoice_supplier_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='sale_type',
            field=models.CharField(choices=[('CS', 'Cash'), ('CR', 'Credit')], default='CR', max_length=10),
        ),
    ]
