# Generated by Django 3.2.13 on 2022-04-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplydeposit_sale_type'),
        ('shop', '0007_purchaseinvoice_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesale',
            name='supplier_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
    ]
