# Generated by Django 3.2.13 on 2022-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220430_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='sale_type',
            field=models.CharField(choices=[('CS', 'Cash'), ('CR', 'Credit')], default='CS', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_d',
            field=models.IntegerField(null=True),
        ),
    ]
