# Generated by Django 3.2.13 on 2022-04-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplydeposit_sale_type'),
        ('shop', '0010_auto_20220430_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='purchasesale',
            name='supplier_d',
            field=models.IntegerField(null=True),
        ),
    ]
