# Generated by Django 3.2.13 on 2022-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220510_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='sale_type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], default='CS', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasesale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasesale',
            name='sale_type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], default='CS', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='sale_type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='sale_type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=10),
        ),
    ]
