# Generated by Django 3.2.8 on 2021-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='sale_type',
            field=models.CharField(choices=[('CS', 'Cash'), ('CQ', 'Cheque')], default='CS', max_length=10),
        ),
    ]
