# Generated by Django 3.2.8 on 2021-11-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_deposit_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='sale_type',
            field=models.CharField(choices=[('CS', 'Cash'), ('CQ', 'Cheque')], max_length=10),
        ),
    ]
