"""pos URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from customers.views import (
    customer_view,
    customer_edit_view,
    customer_delete_view,
    deposit_view,
    deposit_edit_view,
    deposit_delete_view,
    loan_view,
    loan_edit_view,
    loan_delete_view,
    debt_view,
    debt_edit_view,
    debt_delete_view,
    receivable_view,
    payable_view,
    export_receivable,
    view_deposit,
)

from sales.views import (
    sales_report_view,
    credit_report_view,
    invoice_view,
    sales_view,
    view_sales,
    sales_edit_view,
    sales_delete_view,
    credit_invoice_view,
    credit_sale_view,
    credit_sale_edit_view,
    credit_sale_delete_view,
    view_credit,
    # cash_book_view,
    export_csv_sales,
    export_csv_detail_sales,
    export_csv_credit,
    export_csv_detail_credit,
    profit_report_view,
    purchase_report_view,
    export_csv_profit,
    export_csv_profit_monthly,
    get_days,
    purchase_days,
    get_months,
    purchase_months,
)

from accounts.views import (
    login_view,
    logout_view,
    home_view,
    register_view,
    register_edit_view,
    PasswordsChangeView,
    password_success,

)

from shop.views import (
    stock_report_view,
    raw_report_view,
    expenses_view,
    expenses_edit_view,
    expenses_delete_view,
    inventory_view,
    inventory_edit_view,
    inventory_delete_view,
    purchase_sales_view,
    purchase_edit_view,
    purchase_delete_view,
    view_purchase_invoice,
    purchase_invoice_view,
    export_csv_view,
    export_excel_view,
    export_csv_stock,
    supply_view,
    supply_edit_view,
    supply_delete_view,
)

from processing.views import (
    product_view,
    product_edit_view,
    product_delete_view,
    processing_view,
    processing_edit_view,
    process_sales_view,
    process_view_sales,
    process_sales_edit_view,
    process_sales_delete_view,
)

from suppliers.views import (
    supplier_view,
    supplier_edit_view,
    view_supplier_credit,
    credit_view,
    credit_edit_view,
    credit_delete_view,
    supplier_debt_view,
    supplier_debt_edit_view,
    supplier_debt_delete_view,
    supplier_receivable_view,
    supplier_payable_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password/', PasswordsChangeView.as_view(template_name='change_password.html')),
    path('password_success', password_success, name='password_success'),
    path('', login_view),
    path('daily_summary/', profit_report_view),
    path('summary_purchase/', purchase_report_view),
    path('monthly_summary/', get_days),
    path('monthly_purchase_summary/', purchase_days),
    path('yearly_summary/', get_months),
    path('yearly_purchase_summary/', purchase_months),
    path('suppliers', supplier_view),
    path('suppliers/<int:pk>', supplier_edit_view),
    path('credit/receipt/<int:inv>', view_supplier_credit),
    path('supplier_credit', credit_view),
    path('credit/<int:pk>', credit_edit_view),
    path('credit/delete/<int:pk>', credit_delete_view),
    path('receivable/', receivable_view),
    path('payable/', payable_view),
    path('supplier_receivable/', supplier_receivable_view),
    path('supplier_payable/', supplier_payable_view),
    path('export_receivable', export_receivable, name='export-receivable'),
    path('export_csv', export_csv_view),
    path('export_excel', export_excel_view),
    path('export_csv_credit', export_csv_credit, name='export-credit-report'),
    path('export_csv_detail_credit', export_csv_detail_credit, name='export-credit-detail-report'),
    path('export_csv_sale', export_csv_sales, name='export-report'),
    path('export_csv_detail_sale', export_csv_detail_sales, name='export-detail-report'),
    path('export_csv_stock', export_csv_stock, name='export-stock-report'),
    path('export_csv_profit', export_csv_profit, name='export-profit-report'),
    path('export_profit_monthly', export_csv_profit_monthly, name='export-profit-monthly'),
    path('home/', home_view),
    # path('cash_book/', cash_book_view),
    path('logout/', logout_view),
    path('register/', register_view),
    path('register/<int:pk>', register_edit_view),
    path('expenses/', expenses_view),
    path('expenses/<int:pk>', expenses_edit_view),
    path('expenses/delete/<int:pk>', expenses_delete_view),
    path('products', product_view),
    path('products/<int:pk>', product_edit_view),
    path('products/delete/<int:pk>', product_delete_view),
    path('processing', processing_view),
    path('processing/<int:pk>', processing_edit_view),
    path('transfer', supply_view),
    path('transfer/edit/<int:pk>', supply_edit_view),
    path('transfer/delete/<int:pk>', supply_delete_view),
    path('inventory/', inventory_view),
    path('inventory/<int:pk>', inventory_edit_view),
    path('inventory/delete/<int:pk>', inventory_delete_view),
    path('purchase/', purchase_invoice_view),
    path('purchase/edit/<int:pk>', purchase_edit_view),
    path('purchase_invoice/edit/<int:pk>', purchase_edit_view),
    path('purchase_invoice/delete/<int:pk>', purchase_delete_view),
    path('purchase/delete/<int:pk>', purchase_delete_view),
    path('purchase/<int:inv>', view_purchase_invoice),
    path('purchase_invoice/', purchase_sales_view),
    path('customer/', customer_view),
    path('customer/edit/<int:pk>', customer_edit_view),
    path('customer/delete/<int:pk>', customer_delete_view),
    path('deposit/', deposit_view),
    path('deposit/<int:pk>', deposit_edit_view),
    path('deposit/delete/<int:pk>', deposit_delete_view),
    path('loan/', loan_view),
    path('loan/<int:pk>', loan_edit_view),
    path('loan/delete/<int:pk>', loan_delete_view),
    path('debt/', debt_view),
    path('debt/<int:pk>', debt_edit_view),
    path('debt/delete/<int:pk>', debt_delete_view),
    path('supply_debt/', supplier_debt_view),
    path('supply_debt/<int:pk>', supplier_debt_edit_view),
    path('supply_debt/delete/<int:pk>', supplier_debt_delete_view),
    path('paid_sales/', invoice_view),
    path('invoice/', sales_view),
    path('process_invoice/', process_sales_view),
    path('process_invoice/<int:inv>', process_view_sales),
    path('process_invoice/edit/<int:pk>', process_sales_edit_view),
    path('process_invoice/delete/<int:pk>', process_sales_delete_view),
    path('deposit/receipt/<int:inv>', view_deposit),
    path('invoice/<int:inv>', view_sales),
    path('invoice/edit/<int:pk>', sales_edit_view),
    path('invoice/delete/<int:pk>', sales_delete_view),
    path('credit_sales/', credit_invoice_view),
    path('credit_invoice/', credit_sale_view),
    path('credit_invoice/edit/<int:pk>', credit_sale_edit_view),
    path('credit_invoice/delete/<int:pk>', credit_sale_delete_view),
    path('credit_invoice/<int:inv>', view_credit),
    path('stock_report/', stock_report_view),
    path('raw_report/', raw_report_view),
    path('sales_report/', sales_report_view),
    path('credit_report/', credit_report_view),
]
