# Generated by Django 3.2.13 on 2022-04-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditsale',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sale_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_type',
        ),
    ]
