# Generated by Django 3.2.13 on 2022-04-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20220428_0701'),
        ('sales', '0004_auto_20220429_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.product'),
        ),
    ]
